version: '3'
services:
  app:
    container_name: discord-t2s-bot-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - '8080:8080'
    env_file: .env
volumes:
  node_modules:
    driver: 'local'